import {
  CREATE_LIST_REQUEST_FAILED,
  CREATE_LIST_REQUEST_SENT,
  CREATE_LIST_REQUEST_SUCCEEDED,
  DELETE_LIST_REQUEST_FAILED,
  DELETE_LIST_REQUEST_SENT,
  DELETE_LIST_REQUEST_SUCCEEDED,
  FETCH_LISTS_AND_TASKS_REQUEST_SENT,
  FETCH_LISTS_AND_TASKS_REQUEST_SUCCEEDED,
  FETCH_LISTS_AND_TASKS_REQUEST_FAILED,
  UPDATE_LIST_REQUEST_SENT,
  UPDATE_LIST_REQUEST_FAILED,
  UPDATE_LIST_REQUEST_SUCCEEDED,
} from '../../../../action-types'

const isLoading = (state = false, action) => {
  switch (action.type) {
    case CREATE_LIST_REQUEST_SENT:
    case DELETE_LIST_REQUEST_SENT:
    case FETCH_LISTS_AND_TASKS_REQUEST_SENT:
    case UPDATE_LIST_REQUEST_SENT:
      return true
    case CREATE_LIST_REQUEST_FAILED:
    case CREATE_LIST_REQUEST_SUCCEEDED:
    case DELETE_LIST_REQUEST_FAILED:
    case DELETE_LIST_REQUEST_SUCCEEDED:
    case FETCH_LISTS_AND_TASKS_REQUEST_SUCCEEDED:
    case FETCH_LISTS_AND_TASKS_REQUEST_FAILED:
    case UPDATE_LIST_REQUEST_FAILED:
    case UPDATE_LIST_REQUEST_SUCCEEDED:
      return false
    default:
      return state
  }
}

export default isLoading
