import {
  FETCH_LISTS_AND_TASKS_REQUEST_FAILED,
  FETCH_LISTS_AND_TASKS_REQUEST_SENT,
  FETCH_LISTS_AND_TASKS_REQUEST_SUCCEEDED,
  CLOUDINARY_REQUEST_SENT,
  CLOUDINARY_REQUEST_FAILED,
  CLOUDINARY_REQUEST_SUCCEEDED,
  CREATE_IMAGE_REQUEST_SENT,
  CREATE_IMAGE_REQUEST_FAILED,
  CREATE_IMAGE_REQUEST_SUCCEEDED,
  DELETE_IMAGE_REQUEST_SENT,
  DELETE_IMAGE_REQUEST_FAILED,
  DELETE_IMAGE_REQUEST_SUCCEEDED,
} from '../../../../action-types'

const isLoading = (state = false, action) => {
  switch (action.type) {
    case FETCH_LISTS_AND_TASKS_REQUEST_SENT:
    case CLOUDINARY_REQUEST_SENT:
    case CREATE_IMAGE_REQUEST_SENT:
    case DELETE_IMAGE_REQUEST_SENT:
      return true
    case FETCH_LISTS_AND_TASKS_REQUEST_FAILED:
    case FETCH_LISTS_AND_TASKS_REQUEST_SUCCEEDED:
    case CLOUDINARY_REQUEST_FAILED:
    case CLOUDINARY_REQUEST_SUCCEEDED:
    case CREATE_IMAGE_REQUEST_FAILED:
    case CREATE_IMAGE_REQUEST_SUCCEEDED:
    case DELETE_IMAGE_REQUEST_FAILED:
    case DELETE_IMAGE_REQUEST_SUCCEEDED:
      return false
    default:
      return state
  }
}

export default isLoading
